#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 28 14:26:45 2022

@author: juanmeriles
"""
import numpy as np
import matplotlib.pyplot as plt
F = np.array([[2,0,0],[0,1,0],[0,0,1]])

C= F.T@F
[lam2,M] = np.linalg.eig(C)
lam = np.sqrt(lam2)



m = np.linspace(-10,10,10000)
E = np.zeros(len(m))
for i in range(len(m)):
    if m[i] != 0:
        Cm2 = (lam[0]**(m[i]/2))*np.outer(M[:,0],M[:,0])+(lam[1]**(m[i]/2))*\
            np.outer(M[:,1],M[:,1])+(lam[2]**(m[i]/2))*np.outer(M[:,2],M[:,2])
        E[i] = (1/m[i]*(Cm2-np.eye(3)))[0][0]
    else:
        lnC = (np.log(lam[0]**2))*np.outer(M[:,0],M[:,0])+(np.log(lam[1]**2))*\
            np.outer(M[:,1],M[:,1])+(np.log(lam[2]**2))*np.outer(M[:,2],M[:,2])
        E[i] = (1/2)*lnC[0][0]
plt.plot(m,E)
plt.xlabel('m')
plt.ylabel('E11')